### PR TITLE
Update version for the next release (v0.1.3)

### PR DESCRIPTION
**Pull request by alallema**

### CODE REVIEW

**Review by mdubus — COMMENTED** [review]
The version was also changed in `functions/lib/version.js`, but in the `CONTRIBUTING` it's not listed :) 
```
2. To update the version package in all needed files you can run the `version.sh` script with the version number in argument: `"X.X.X"`. If you want to modify it by hand you have to update the version in the following files:
- [`package.json`](/package.json).
- [`package.json`](/functions/package.json) in the functions directory.
- [`extension.yaml`](/extension.yaml).
- [`version.ts`](/functions/src/version.ts).
```

**Comment by alallema** [comment]
> The version was also changed in `functions/lib/version.js`, but in the `CONTRIBUTING` it's not listed :)
> 
> ```
> 2. To update the version package in all needed files you can run the `version.sh` script with the version number in argument: `"X.X.X"`. If you want to modify it by hand you have to update the version in the following files:
> - [`package.json`](/package.json).
> - [`package.json`](/functions/package.json) in the functions directory.
> - [`extension.yaml`](/extension.yaml).
> - [`version.ts`](/functions/src/version.ts).
> ```

Yes, because the `version.js` is generated by the typescript `build`. So you don't have to edit any `js` file.

**Review by mdubus — DISMISSED** [review]
LGTM 🥳

**Comment by alallema** [comment]
bors merge

**Pull request merged**
