### PR TITLE
Update version for the next release (v0.1.2)

### PR DESCRIPTION
**Pull request by alallema**

### CODE REVIEW

**Comment by curquiza** [comment]
Is the contributing.md still up-to-date since we have a CI to publish automatically?

**Comment by alallema** [comment]
> Is the contributing.md still up-to-date since we have a CI to publish automatically?

Is published only on `NPM`, not on Firebase, but maybe we should say to try the package with `NPX` before publishing the release and `Firebase`

**Comment by curquiza** [comment]
Yes indeed, regarding what you said the CONTRIBUTING could be improved :)

**Review by curquiza — APPROVED** [review]

**Comment by alallema** [comment]
> Yes indeed, regarding what you said the CONTRIBUTING could be improved :)

Alright I create a PR on the Contributing I will improve it

**Comment by alallema** [comment]
bors merge

**Pull request merged**
