### PR TITLE
Fix geo point with tests

### LINKED ISSUE #143: Meilisearch _geo consitency with with Firestore Geopoint
For _geoRadius to work, the current documentation and workings of Meilisearch requires Geopoint fields in firestore to be renamed as _geo. However, when it comes to the "lat" & "lng" field name formats. Firestore does not allow renaming of these fields. These fields are named "_latitude" & "_longitude" respectively by Firestore. I was unable to do a _geoRadius search on Meiliesearch. 

Steps to reproduce the issue: 

1. Install Meilisearch on GCP   - [long story short, it works]
2. Create new index and add "_geo" to "filterableAttributes" settings -  [Works]
3. Install Meilisearch Firestore extension. [Search queries return correct results, including "_geo" fields but with "_latitude" & "_longitude". - [Works]
4. Add test documents with _geo in Firestore. - [Works]
5. Run empty q search without filter - [Works]
6. Run empty q search with {"filter": "_geoRadius( <latitude>, <longitude>, <radius in meters>)"} - [No results returned]

No results returned even if same value as the document are passed. I don't know if it's because Meilisearch is looking for "lat" & "lng" and can't find anything or something else. Either way, I could find any issues or documentation on this. 

I also came across [this](https://github.com/meilisearch/firestore-meilisearch/issues/16) issue. I'm not sure if anything has been rewritten but the documentation is not update in that case.

### PR DESCRIPTION
**Pull request by oplik0**
# Pull Request

## Related issue
Fixes #143 

## What does this PR do?
- this is a corrected version of #147 - the issue with tests was a Jest issue that appears to have been fixed in v28.
- While experimenting with this, I also updated the firebase packages - decided to leave them at newer versions instead of rolling these changes back
- Made some small changes to tests to align them with output format of `adaptFields`
- Re-added logging geopoint information to `adaptFields` to align with tests
- Added eslint-import-resolver-typescript, because without it the eslint import plugin doesn't work with `exports` in `package.json` which marked all `firebase-admin` imports as lint errors.

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

### CODE REVIEW

**Comment by bidoubiwa** [comment]
Hey @oplik0 

Thanks a lot for this contribution 🙏

**Comment by oplik0** [comment]
It seems the snapshot test will need a flag added for CI:
> New snapshot was not written. The update flag must be explicitly passed to write a new snapshot.
> This is likely because this test is run in a continuous integration (CI) environment in which snapshots are not written by default.

Tests pass locally for me and in a fresh Codespaces environment:
working in Codespaces
I'll look into fixing this in an hour or two.

**Comment by oplik0** [comment]
Well, turns out there are two simple solutions:
- the recommended way is apparently to remove the snapshots from `.gitignore` and add them to the repository
- or if updating the snapshots is preferred `--updateSnapshot` flag can just be added to arguments in `test:coverage` in `package.json`, overriding the default CI behavior.

Please let me know which one you prefer

**Comment by bidoubiwa** [comment]
> For now I decided to follow Jest recommendations and commit the snapshot files. Please let me know if you prefer to leave them ignored.

Good for me :)

**Review by bidoubiwa — APPROVED** [review]
Very nice 🔥

**Comment by bidoubiwa** [comment]
bors merge

**Pull request merged**
