### PR TITLE
replaced the old URL and checked other files for its presence 

### LINKED ISSUE #130: Update the readme's with the new extension link to the marketplace
**Description**
Previously we were not added in the official Marketplace of firebase. Which is the case today.
In our README we still point to the old URL: `https://console.firebase.google.com/project/_/extensions/install?ref=meilisearch/firestore-meilisearch`. This should be changed with the following link `https://extensions.dev/extensions/meilisearch/firestore-meilisearch`

The link may be present in other files than the `README.md`. Please check.

### PR DESCRIPTION
**Pull request by Pragya2056**
# Pull Request

## Related issue
Fixes #130 

## What does this PR do?
- Replaces the old URL `https://console.firebase.google.com/project/_/extensions/install?ref=meilisearch/firestore-meilisearch` with `https://extensions.dev/extensions/meilisearch/firestore-meilisearch`
- There are also some formatting changes to make the Readme look nicer. Hope they won't be a problem. 

## PR checklist
Please check if your PR fulfills the following requirements:
- [ Yes] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [Yes ] Have you read the contributing guidelines?
- [Yes ] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

### CODE REVIEW

**Comment by Pragya2056** [comment]
@bidoubiwa

**Review by bidoubiwa — CHANGES_REQUESTED** [review]
Hey @Pragya2056 thanks for contributing 🔥

- The geosearch links formating is not fixed.
- I prefer keeping the old formating of the bulletpoints

Some changes are nice and the link to the marketplace is working :)

**Comment by Pragya2056** [comment]
> Hey @Pragya2056 thanks for contributing 🔥
> 
> * The geosearch links formating is not fixed.
> * I prefer keeping the old formating of the bulletpoints
> 
> Some changes are nice and the link to the marketplace is working :)

What are the new required changes?

**Comment by bidoubiwa** [comment]
The one I just mentioned 😅

**Comment by Pragya2056** [comment]
Thank you!!!

**Review by bidoubiwa — APPROVED** [review]
bors merge

**Comment by bidoubiwa** [comment]
_This message is sent automatically_

Thanks again for contributing to Meilisearch :heart:
If you are participating in [Hacktoberfest](https://blog.meilisearch.com/contribute-hacktoberfest-2022/), and you would like to receive some gift from Meilisearch too, please complete [this form](https://meilisearch.typeform.com/to/idt5qugY).

**Pull request merged**
